version: "3.9"
services:
  api:
    container_name: api
    profiles:
      - prod
    build:
      context: .
      dockerfile_inline: |
        FROM node:18.16.0-alpine
        WORKDIR /usr/src/app
        COPY ./node_modules ./node_modules
        COPY ./dist/apps/api package.json .prod.env .
        ENV NODE_ENV production
        EXPOSE 3000
        CMD [ "node", "main.js" ]
    ports:
      - "3000:3000"
    restart: always
  ws:
    container_name: ws
    profiles:
      - prod
    build:
      context: .
      dockerfile_inline: |
        FROM node:18.16.0-alpine
        WORKDIR /usr/src/app
        COPY ./node_modules ./node_modules
        COPY ./dist/apps/ws package.json .prod.env .
        ENV NODE_ENV production
        EXPOSE 5000
        CMD [ "node", "main.js" ]
    volumes:
      - ~/storage/geo:/usr/src/app/geo
    ports:
      - "5000:5000"
    restart: always
  web:
    container_name: web
    profiles:
      - prod
    build:
      context: .
      dockerfile_inline: |
        FROM node:18.16.0-alpine
        WORKDIR /usr/src/app
        COPY ./dist/apps/web .
        RUN npm install --global serve
        EXPOSE 4200
        CMD [ "serve", ".", "-p", "4200", "-s" ]
    ports:
      - "4200:4200"
    restart: always
  reverse-proxy:
    image: nginx:alpine
    container_name: reverse-proxy
    profiles:
      - prod
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/ssl/shqipet:/etc/ssl/shqipet
    restart: always
  db:
    image: postgres:14-alpine
    container_name: db
    profiles:
      - dev
      - prod
    ports:
      - ${DB_PORT}:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
  db-admin:
    image: dpage/pgadmin4
    container_name: db-admin
    profiles:
      - dev
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin.servers.json:/data/pgadmin.servers.json
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_SERVER_JSON_FILE=//data/pgadmin.servers.json
volumes:
  db:
