version: "3.9"
services:
  users:
    build:
      context: .
      dockerfile_inline: |
        FROM node:18.16.0-alpine
        WORKDIR /usr/src/app
        COPY ./node_modules ./node_modules
        COPY ./dist/apps/users package.json .prod.env geo.mmdb .
        ENV NODE_ENV production
        EXPOSE 3000
        CMD [ "node", "main.js" ]
    ports:
      - "3000:3000"
    restart: always
  web:
    build:
      context: .
      dockerfile_inline: |
        FROM node:18.16.0-alpine
        WORKDIR /usr/src/app
        COPY ./dist/apps/web .
        RUN npm install --global serve
        EXPOSE 4200
        CMD [ "serve", ".", "-p", "4200" ]
    ports:
      - "4200:4200"
    restart: always
  reverse-proxy:
    image: nginx:alpine
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/ssl/shqipet:/etc/ssl/shqipet
    network_mode: host
    restart: always
