version: "3.9"
services:
  reverse-proxy:
    image: nginx:alpine
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/ssl/shqipet:/etc/ssl/shqipet
    restart: always
