version: "3.9"
services:
  api:
    container_name: api
    build:
      context: .
      dockerfile_inline: |
        FROM node:18.16.0-alpine
        WORKDIR /usr/src/app
        COPY ./node_modules ./node_modules
        COPY ./dist/apps/api package.json .prod.env .
        ENV NODE_ENV production
        EXPOSE 3000
        CMD [ "node", "main.js" ]
    ports:
      - "3000:3000"
    restart: always
  chat:
    container_name: chat
    build:
      context: .
      dockerfile_inline: |
        FROM node:18.16.0-alpine
        WORKDIR /usr/src/app
        COPY ./node_modules ./node_modules
        COPY ./dist/apps/chat package.json .prod.env .
        ENV NODE_ENV production
        EXPOSE 5000
        CMD [ "node", "main.js" ]
    volumes:
      - ~/storage/geo:/usr/src/app/geo
    ports:
      - "5000:5000"
    restart: always
  web:
    container_name: web
    build:
      context: .
      dockerfile_inline: |
        FROM node:18.16.0-alpine
        WORKDIR /usr/src/app
        COPY ./dist/apps/web .
        RUN npm install --global serve
        EXPOSE 4200
        CMD [ "serve", ".", "-p", "4200", "-s" ]
    ports:
      - "4200:4200"
    restart: always
  reverse-proxy:
    image: nginx:alpine
    container_name: reverse-proxy
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/ssl/shqipet:/etc/ssl/shqipet
    restart: always
