name: Deployment workflow
on:
  workflow_dispatch:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: appleboy/ssh-action@master
      with:
        username: ${{ vars.USERNAME }}
        host: ${{ vars.HOST }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        script: |
          cd projects
          rm -rf shqipet
          git clone git@github.com:alb-xh/shqipet.git
          cd shqipet
          echo "${{ vars.CONFIG }}" >> .prod.env
          nvm install
          npm install --omit=dev
